name: Auto Build & Release Rust Binary (latest)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
     
      - name: Install Rust target
        shell: bash
        run: rustup target add ${{ matrix.target }}

      - name: Build release binary
        shell: bash
        run: |
          cargo build --release --target ${{ matrix.target }}
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            bin="target/${{ matrix.target }}/release/genshin_script.exe"
          else
            bin="target/${{ matrix.target }}/release/genshin_script"
          fi
          echo "BIN=$bin" >> $GITHUB_ENV

      - name: Zip the binary
        shell: bash
        run: |
          pd="genshin_script-latest-${{ matrix.target }}"
          mkdir -p "$pd"
          mv "$BIN" "$pd"
          7z a "$pd.zip" "$pd"
          certutil -hashfile "$pd.zip" SHA256 > "$pd.zip.sha256"
          echo "ASSET=$pd.zip" >> $GITHUB_ENV
          echo "ASSET_SUM=$pd.zip.sha256" >> $GITHUB_ENV

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: |
            ${{ env.ASSET }}
            ${{ env.ASSET_SUM }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Binaries
        uses: actions/download-artifact@v4
        with:
          path: build

      - name: Check Files Before Release
        run: |
          ls -l build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GENSHIN_IMPACT_RELEASE }}
