name: Auto Build & Release Rust Binary

on:
  push:
    tags:
      - "v*"  # Triggers only when a tag (e.g., v1.0.0) is pushed

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]  # Build for multiple platforms
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable  # Uses the latest stable Rust version

      - name: Build Release Binary
        run: cargo build --release         

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: target/release/genshin_script.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Binaries
        uses: actions/download-artifact@v4
        with:
          path: build/

      - name: Zip Binaries
        run: |
          cd build/
          zip -r genshin_script-${{ github.ref_name }}.zip */

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/genshin_script-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
